namespace WinRTComponent
{
    [default_interface]
    runtimeclass GraphicsCapture
    {
        GraphicsCapture();

        UInt8[] GetActiveWindow(UInt64 hwnd, out Int32 width, out Int32 height);
    }
}
